application: battleline-online
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /stylesheets
  static_dir: public/stylesheets

- url: /javascripts
  static_dir: public/javascripts

- url: /images
  static_dir: public/images

- url: /lobby($|/.*)
  script: app/controllers/lobby.py

- url: /debug($|/.*)
  script: app/controllers/debug.py
  login: admin

- url: /game($|/.*)
  script: app/controllers/game.py
  login: required

- url: /
  script: app/controllers/misc.py
